vich_uploader:
    db_driver: orm

    mappings:
       header_images:
           uri_prefix: /images/header
           upload_destination: '%kernel.project_dir%/public/images/header'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
